### ISSUE TITLE
Tian Xiaoliang's comment.

### ISSUE THREAD

**Issue by CurryTXL** [huangyaowei/NumGuess#1]
I think when you enter the 3 numbers that you guess you can use an array to contain them instead of three variables.This can help you simplify your code and using array replaces the overmuch if-else structures by the for or while loop.

**Comment by yuralty** [comment]
Function is good, but code style is far from readable. I just name a few here:
1. when you use braces "{}", normally we will align a pair of braces to the same column, for example:
      if (.......)
      {
             ........
      }
Otherwise people do not know when your if/for/while ends.
2. Align problem again. For lines like 9 and 15, they both have only one tab but they are not aligned properly as my view.
3. Please try not to write code like if(....) {...;...;...;} in the same line. It is fine when what you wanna do within {} is very simple but it will be terrible when code gets complicated.

And another small tip: 
for line 21 and 22, you can simply write:
while(Asking())
{
    ......
}
